### ISSUE TITLE
Hide map on Detail page if value is empty

### ISSUE THREAD

**Issue by scottybo** [GeneaLabs/nova-map-marker-field#13]
On occasion we don't have location data for a particular Model, so on the Detail page the map is defaulting to long/lat 0.

Instead, if the field has no value could we hide the map altogether and have an output such as "Location data not supplied"?

**Comment by mikebronner** [comment]
@scottybo  Good point. I work that into the next update.

**Comment by mikebronner** [comment]
This should now be fixed in release 0.1.6. Please let me know how it works for you.
