### ISSUE TITLE
Geocode into address

### ISSUE THREAD

**Issue by Reached** [GeneaLabs/nova-map-marker-field#16]
Hey @mikebronner ,

Well done on the package!

Is it possible to reverse geocode with this? So that I can get an address from coordinates?

**Comment by mikebronner** [comment]
Hi @Reached, this package doesn't do GeoCoding. For that I recommend https://github.com/geocoder-php/GeocoderLaravel which is perfectly suited to reverse-geocode your locations to addresses in PHP. You could trigger this to automatically happen in a model observer before saving.

**Comment by Reached** [comment]
Thanks @mikebronner, good suggestion !
