### ISSUE TITLE
Option to set zoom level

### ISSUE THREAD

**Issue by checkerschaf** [GeneaLabs/nova-map-marker-field#18]
Hey,

it would be very nice to set the default zoom level. Without it kinda ruins the workflow so it would be very nice to add this option.
It's a great package so far, I'll see if I can contribute later.

Thanks and hava a nice day :)

**Comment by mikebronner** [comment]
@checkerschaf Thats a great suggestion, thanks!

**Comment by mikebronner** [comment]
@checkerschaf Try release 0.1.9. Added default zoom and coordinate settings. Let me know how it works for you. :) Thanks again for the suggestion.
