### ISSUE TITLE
Feature: Default settings for all instances

### ISSUE THREAD

**Issue by vbezruchkin** [GeneaLabs/nova-map-marker-field#21]
Hi,

Thanks again for the great plugin. 
Please add configuration for default MapMarker values, so I don't need to setup it for every model I have.

Example:
- I have several models located in one city
- I use MapMarker in several files with the default values

It would be easier for my case to have just one default configuration (latitude, longitude, zoom, etc.) and it would be applied to all calls.

Thanks in advance.

**Comment by mikebronner** [comment]
Is this not what you mean?https://github.com/GeneaLabs/nova-map-marker-field#default-settings

**Comment by vbezruchkin** [comment]
No, I've seen that. But I guess I need to setup this every time I create a field, right?

I might have 10 map fields in different Nova resources. I'd like to have ONE common default settings rather configure default values every time I create a new field. It's like your default 12, and 0/0 for coordinates.

Thanks

**Comment by mikebronner** [comment]
I see. You can do this yourself already. Set up a config file, lets say `config\settings.php`:
```php
return [
    "map_defaults" => [
        "latitude" => "xxxxxxx",
        "longitude" => "xxxxxxx",
        "zoom" => 5,
    ],
];
```

Then in your nova resources:
```php
MapMarker::make("Location")
    ->defaultZoom(config("settings.map_defaults.zoom"))
    ->defaultLatitude(config("settings.map_defaults.latitude"))
    ->defaultLongitude(config("settings.map_defaults.longitude")),
```

Those kind of things are very app-dependent, so it's best you handle that as you see fit. I don't want to impose any kind of convention like that, as I have already exposed the functions necessary to let people do what they want. :)

Let me know how that works.

**Comment by vbezruchkin** [comment]
Thanks for the advice. Yes, this seems reasonable, and I thought of it. But I'd like to go even further.

Let's say we have config file `config\mapmarker.php` with the following content:
```php
return [
    "map_defaults" => [
        "latitude" => "xxxxxxx",
        "longitude" => "xxxxxxx",
        "zoom" => 5,
    ],
];
```

and when I create a new Nova field, these settings would be applied automatically for all the resources. This would allow to get rid of default duplication in each resource:
```php
MapMarker::make("Location"),
```

Not a big deal though, of course I can live with default values in several resource files. But in my case it would be easier to have ONE global settings file, without setting default values in each resource separately.

**Comment by mikebronner** [comment]
@vbezruchkin No problem, I understand. At this time automatically applying default values from configs is not something I am considering, as I believe it to be out of the scope of this package.

Thanks for bringing this up, though! :)
