### ISSUE TITLE
Restrictive dependency for Nova as local folder

### ISSUE THREAD

**Issue by vbezruchkin** [GeneaLabs/nova-map-marker-field#22]
Hi again,

Looks like the problem, outlined in #17 is still persistent. We have the same problem on some other dev environments. 

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - genealabs/nova-map-marker-field dev-master requires laravel/nova 2.* -> no matching package found.
    - genealabs/nova-map-marker-field dev-master requires laravel/nova 2.* -> no matching package found.
    - Installation request for genealabs/nova-map-marker-field dev-master -> satisfiable by genealabs/nova-map-marker-field[dev-master].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

Looks like the dependency does not work well, when you include Nova as a local folder:
```
    "repositories": {
        "laravel/nova": {
            "type": "path",
            "url": "./nova"
        }
    },
```
it worked fine for me, when I followed your advise and used Nova from regular registry. 

Anyhow, quick research shows that if I switch your package composer dependency to * it works just fine. I checked 6 most popular packages from https://novapackages.com/ and they all don't have nova dependency at all or just `"laravel/nova": "*"` 

Please consider to change your package dependency to *

Thanks in advance.

**Comment by vbezruchkin** [comment]
Looks like it's similar to https://stackoverflow.com/questions/49287911/composer-dependency-on-local-repository so it's more a compose thing, but the pull request would indeed help as it's the only package I have issue with :) Thanks!

**Comment by mikebronner** [comment]
@vbezruchkin Thanks for raising this issue. I will take a look at it over the next few days.

**Comment by vbezruchkin** [comment]
thanks, Mike :)
