### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by timcv** [GeneaLabs/nova-map-marker-field#24]
Hi,

What column type would you use for the migration?

Thanks for a promising package!

//Tim

**Comment by mikebronner** [comment]
You basically have two fields, one for latitude and one for longitude. I would recommend:
```php
            $table->decimal("latitude", 15, 12)->nullable();
            $table->decimal("longitude", 15, 12)->nullable();
```

**Comment by timcv** [comment]
Thank you!

You should att these details to the docs.

Thanks for an awesome field!

//Tim
