### ISSUE TITLE
Assets not compiled for production

### ISSUE THREAD

**Issue by checkerschaf** [GeneaLabs/nova-map-marker-field#26]
Hi,
I've just seen that the nova assets aren't compiled for production.
The console contains development warnings for vue.

Would be nice if you can fix it very quick 😄 
If you don't have any time atm I could do it later.

Thanks

**Comment by mikebronner** [comment]
Fix incoming ASAP.

**Comment by mikebronner** [comment]
Should be fixed in 0.1.13. Let me know how it works for you.

**Comment by checkerschaf** [comment]
@mikebronner Yes it does! Thanks a lot for the hot fix 👍
