### ISSUE TITLE
OSM tile provider, load over https

### ISSUE THREAD

**Issue by tanthammar** [GeneaLabs/nova-map-marker-field#27]
v 0.1.13

Looks like this old issue is unresolved.

#14 

Error:
```
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure image '<URL>'. This content should also be served over HTTPS.
```
```
... insecure image 'http://c.tile.osm.org/12/2047/2047.png'. This content should also be served over HTTPS.
```

**Comment by mikebronner** [comment]
@tanthammar Thanks for bringing this up. I just confirmed that it was fixed in one spot, but not another. I will get this updated ASAP.

**Comment by mikebronner** [comment]
@tanthammar Give release 0.1.14 a try and let me know how it works for you.
