### ISSUE TITLE
new `isRequired` method in laravel nova field causes error

### ISSUE THREAD

**Issue by zareismail** [GeneaLabs/nova-map-marker-field#28]
nova version: 2.5.0

this package uses an array for field `attribute` that causes error `illegal offset type` when the nova check `isReuired` in nova field.

**Comment by mikebronner** [comment]
@zareismail Thanks for reporting this issue. For now use the old way of making a field required, until this is fixed. :)
```php
->rules("required")
```

**Comment by zareismail** [comment]
> @zareismail Thanks for reporting this issue. For now use the old way of making a field required, until this is fixed. :)
> 
> ```
> ->rules("required")
> ```

this error happening without uses rule on the field. when appended a rule to the field this error never happened

**Comment by mikebronner** [comment]
Ah, thanks for the clarification. This must be due to changes in Nova 2.5. I will try to get that sorted out today.

**Comment by mikebronner** [comment]
@zareismail This should now be fixed in release 0.1.15. Please try it and let me know how it works for you.

Thanks!
