### ISSUE TITLE
Is it possible to put several markers in a map ?

### ISSUE THREAD

**Issue by xoco70** [GeneaLabs/nova-map-marker-field#43]
Hi, 

I manage an app for collective autoconsumptions. There is one producer with solar panels on his roof, and several consumers that will consume his local energy. 

When showing detail of each consumers, I can manage it easily, but when I need to show a map for the operation with all actors ( I can have a lot of consumers / producers ) in a 2 km diameter, I don't know how to do it. Circle would be quite nice to draw the limits of  operation ( the 2 km diameter ) but I don't know if it is possible to add several markers in a map ? Is it ?

**Comment by mikebronner** [comment]
Hi @xoco70, thanks for using this package. This package is only meant for a single marker. However, there is functionality to add radius circles, see the ReadMe for "Center Circle".

**Comment by xoco70** [comment]
Yep, I saw the circle, which is great, but I need several markers inside the circle ! Thanks anyway ! And thanks for the plugin ! I will use it for other uses cases
