### ISSUE TITLE
TypeError: Cannot create property 'latitude' on string

### ISSUE THREAD

**Issue by MohmmedAshraf** [GeneaLabs/nova-map-marker-field#44]
Hello, thanks for the package.

I got this error in the browser console in resource details when I try to move the map or zoom in and out.

![image](https://user-images.githubusercontent.com/44909285/95266879-62922a80-0834-11eb-91f8-c02304222d2e.png)

**Comment by mikebronner** [comment]
Hi @MohmmedAshraf, please provide the following:
- PHP version
- Laravel version
- Package version
- Nova version

Full stacktrace from `storage/logs/laravel.log` if one exists.

**Comment by MohmmedAshraf** [comment]
Hello @mikebronner that's was fast 😄  thanks
- PHP v7.4.11
- Laravel Framework v8.9.0
- Package version v0.3.0
- Nova v3.11.1

there is no laravel.log exists

**Comment by mikebronner** [comment]
Thanks for the follow-up. There may be a new incompatibility with a recent Nova update. Give me some time to research this.

**Comment by Dontorpedo** [comment]
PHP v7.4
Laravel v8.9
Package: v.0.3.0
Nova: 3.12

same issue

**Comment by parelius** [comment]
Same issue using

- PHP 7.4
- Laravel 8.21
- Nova 3.15
- Package 0.30.0

Using Chrome on Mac lets me display and update map correctly, althoug the error messages appear in browser console.
Using Firefox or Safari on Mac fails in displaying/updating the map.
