### ISSUE TITLE
Laravel 6 support on 0.2.2

### ISSUE THREAD

**Issue by donkfather** [GeneaLabs/nova-map-marker-field#47]
Hello,

Thank you for the package. I was wondering is there any specific reason why version 0.2.2 doesn't support Laravel 6 ? 
I forked it and changed the composer.json file to allow Laravel 6 and haven't encountered any issues so far.
I'm asking because it might be something I missed.

Thank you

**Comment by mikebronner** [comment]
Hi @Donkfather,
No specific reason at this point. As a general rule, I only support the latest version of Laravel. Further, I might only support more recent versions of PHP in order to take advantage of new functionality. If you forked it and it works, you should be OK. :)
