### ISSUE TITLE
Nova is required for?

### ISSUE THREAD

**Issue by StrangerGithuber** [GeneaLabs/nova-map-marker-field#49]
Hello
I am trying to installing but yeah it is asking for nova. The nova is not good for me because must pay for every projects and on the localhost it is problematic if I am trying to test things and after uploading the files to productive webserver.
Which way this package is using the Nova? Why do I need Nova?
Can't I use this package without nova?

Thank you for the answer.

**Comment by mikebronner** [comment]
Hi @StrangerGithuber, as this package will only work in Laravel Nova, it requires Nova. This package will not work in Laravel alone, sorry.
