### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by mziraki** [GeneaLabs/nova-map-marker-field#60]

**Comment by nicko170** [comment]
Hello @mziraki 
Opened #61 for this.

**Comment by mikebronner** [comment]
This is now available in release 0.4.0. Thank you @nicko170!

**Comment by mziraki** [comment]
@mikebronner is there any reason for dropping of laravel 8 support?

**Comment by mikebronner** [comment]
I only support current laravel versions.if you still need to use the laravel 8 version, you can use the older version of the package, or make a fork and adjust as necessary. Since this is still in beta, I am not concerned with LTS support.
