### ISSUE TITLE
Marker doesn't stay in correct spot when zooming with scroll wheel on Detail view

### ISSUE THREAD

**Issue by calvinps** [GeneaLabs/nova-map-marker-field#7]
The marker is locked to the middle of the screen, but if you put your mouse near the corner of the image and scroll in/out the frame shifts to the left/right, but the marker bounces back to the center of the map, which ends up being in the wrong location. Starting with the map zoomed in to street level, you can zoom out with your scroll wheel on your mouse and move the marker clear across the globe. 

Suggested fix: don't force the marker to be "centered" on the detail view, but keep it centered on the edit/create view.

**Comment by mikebronner** [comment]
@calvinps Can you make a quick video of the problem you describe and post it? That would help tremendously. Thanks for reporting this. :)

**Comment by mikebronner** [comment]
PS: I'm currently working on another bug fix, and will try to fix this for release 0.1.2 later today.

**Comment by mikebronner** [comment]
@calvinps I just found what you meant. No need for the video.

**Comment by mikebronner** [comment]
@calvinps This should now be fixed in release 0.1.2. Please let me know how that works for you. Thanks again for bringing this to my attention. :)

**Comment by calvinps** [comment]
@mikebronner works great, thanks for the quick bug fix and new version release! Was also going to report the update bug but glad to see that is worked in too.
