### ISSUE TITLE
I'm on Laravel 9^ but I still am not able to install this package

### ISSUE THREAD

**Issue by maajidz** [GeneaLabs/nova-map-marker-field#71]
According to the answer provided by you in [Previous Issue](https://github.com/GeneaLabs/nova-map-marker-field/issues/70), I updated Laravel but Im still getting the following error. Please Help. If there is a way to install this package on Nova 4^, Please guide us with that.
<img width="1508" alt="Screenshot 2022-10-17 at 12 01 28 AM" src="https://user-images.githubusercontent.com/13271535/196052019-5f1ca531-5a56-4946-8d95-1b4095344185.png">

**Comment by mikebronner** [comment]
@maajidz unfortunately we do not support Laravel Nova 4 yet. I will be happy to support it if someone can send in a PR -- unfortunately I have not purchased a license for 4, as I no longer use it. I am considering marking this package as obsolete. I apologize for the inconvenience this is causing you, and would encourage you to check here for similar packages that work in Nova 4: https://novapackages.com
